name: JensenHealth
favicon: null
layout_spectrum: 0.62844
typography_spectrum: 0.2758158100768924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c4f96'
    - '#ffffff'
    - '#3970a8'
    - '#a8c1da'
    - '#6793be'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
