name: JensenHealth
favicon: null
layout_spectrum: 0.63437
typography_spectrum: 0.94018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#616f72'
    - '#ffffff'
    - '#d4d7d8'
    - '#899496'
    - '#b4babc'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
